modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="burnt"
version="1.9.4"
displayName="Burnt Basic 1.9.4 Forge 1.20.1"
updateJSONURL="https://github.com/pxlbnk/burnt-1.8.0/blob/8a532a9be3385ab08c74f55f21cd8f25f5a2f031/burnt_update.json"
displayURL="https://discord.com/invite/NUqTwsfTzn"
logoFile="logo.png"
credits="By Pixelbank with MCreator"
authors="Pixelbank, MCreator"
description="A Vanilla fire enhancing mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.burnt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.burnt]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration