/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thebackwoods.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.thebackwoods.item.*;
import net.mcreator.thebackwoods.TheBackwoodsMod;

public class TheBackwoodsModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(TheBackwoodsMod.MODID);
	public static final DeferredItem<Item> BACKWOODS;
	public static final DeferredItem<Item> SPLINTER_SPAWN_EGG;
	public static final DeferredItem<Item> HOLLOW_SPAWN_EGG;
	public static final DeferredItem<Item> LOG_SPLINTER_SPAWN_EGG;
	public static final DeferredItem<Item> ASH_WEAVER_SPAWN_EGG;
	public static final DeferredItem<Item> ASH_ROSE;
	public static final DeferredItem<Item> FADED_BLOCK;
	public static final DeferredItem<Item> PLAQUE;
	public static final DeferredItem<Item> SEEP;
	public static final DeferredItem<Item> PALE_REMEDY;
	public static final DeferredItem<Item> ROT_SPAWN_EGG;
	public static final DeferredItem<Item> ROTTEN_OAK_PLANKS;
	public static final DeferredItem<Item> ROTTEN_OAK_WOOD;
	public static final DeferredItem<Item> ROTTEN_OAK_LOG;
	public static final DeferredItem<Item> GEODE_TELEPORTER;
	public static final DeferredItem<Item> ROTTEN_OAK_STAIR;
	public static final DeferredItem<Item> ROTTEN_OAK_SLAB;
	public static final DeferredItem<Item> ROTTEN_OAK_FENCE;
	public static final DeferredItem<Item> ROTTEN_OAK_TRAPDOOR;
	public static final DeferredItem<Item> ROTTEN_STICK;
	public static final DeferredItem<Item> SPLINTER_SHARD;
	public static final DeferredItem<Item> ROTTEN_SWORD;
	public static final DeferredItem<Item> HEARTWOOD_SHARD;
	public static final DeferredItem<Item> HEARTWOOD_ROTTEN_SWORD;
	public static final DeferredItem<Item> ROTTEN_AXE;
	public static final DeferredItem<Item> ROTTEN_PICKAXE;
	public static final DeferredItem<Item> ROTTEN_SHOVEL;
	public static final DeferredItem<Item> ROTTEN_HOE;
	public static final DeferredItem<Item> ROT_EFFIGY;
	public static final DeferredItem<Item> ROTTEN_OAK_BUTTON;
	public static final DeferredItem<Item> ROTTEN_OAK_GATE;
	public static final DeferredItem<Item> ROTTEN_OAK_PRESSURE_PLATE;
	public static final DeferredItem<Item> PALE_DRAUGHT_BOTTLE;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_OAK_WOOD;
	public static final DeferredItem<Item> BLINDSPOT_SPLINTER_SPAWN_EGG;
	public static final DeferredItem<Item> BLINDSPOT_SPLINTER_SPAWNER;
	public static final DeferredItem<Item> FADED_SWORD;
	public static final DeferredItem<Item> FADED_AXE;
	public static final DeferredItem<Item> FADED_PICKAXE;
	public static final DeferredItem<Item> FADED_HOE;
	public static final DeferredItem<Item> FADED_SHOVEL;
	public static final DeferredItem<Item> FADED_BREAD;
	public static final DeferredItem<Item> FADED_APPLE;
	public static final DeferredItem<Item> FADED_GOLDEN_APPLE;
	public static final DeferredItem<Item> FADED_CARROT;
	public static final DeferredItem<Item> FADED_GOLDEN_CARROT;
	public static final DeferredItem<Item> FADED_COOKED_BEEF;
	public static final DeferredItem<Item> FADED_WHEAT;
	public static final DeferredItem<Item> FADED_COOKED_CHICKEN;
	public static final DeferredItem<Item> FADED_COOKIE;
	public static final DeferredItem<Item> FADED_POTATO;
	public static final DeferredItem<Item> FADED_BAKED_POTATO;
	public static final DeferredItem<Item> FADED_MELON_SLICE;
	public static final DeferredItem<Item> FADED_PUMPKIN_PIE;
	public static final DeferredItem<Item> FADED_IRON_INGOT;
	public static final DeferredItem<Item> FADED_GOLD_INGOT;
	public static final DeferredItem<Item> FADED_COPPER_INGOT;
	public static final DeferredItem<Item> FADED_NETHERITE_INGOT;
	public static final DeferredItem<Item> FADED_GOLD_NUGGET;
	public static final DeferredItem<Item> FADED_MUTTON;
	public static final DeferredItem<Item> FADED_COOKED_MUTTON;
	public static final DeferredItem<Item> FADED_COOKED_PORKCHOP;
	public static final DeferredItem<Item> FADED_PORKCHOP;
	public static final DeferredItem<Item> FADED_RAW_BEEF;
	public static final DeferredItem<Item> FADED_RAW_CHICKEN;
	public static final DeferredItem<Item> FADED_RABBIT;
	public static final DeferredItem<Item> FADED_COOKED_RABBIT;
	public static final DeferredItem<Item> FADED_COD;
	public static final DeferredItem<Item> FADED_COOKED_COD;
	public static final DeferredItem<Item> THE_PETRIFIED_WEALD;
	public static final DeferredItem<Item> PETRIFIED_LOG_SPLINTER_SPAWN_EGG;
	public static final DeferredItem<Item> PETRIFIED_WEALD_FOLIAGE;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_SWORD;
	public static final DeferredItem<Item> PETRIFIED_BARK;
	public static final DeferredItem<Item> SHARPENED_SPLINTER_SHARD;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_OAK_LOG;
	public static final DeferredItem<Item> PETRIFIED_STRIPPED_ROTTEN_OAK_LOG;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_AXE;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_OAK_PLANKS;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_OAK_STAIRS;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_OAK_SLAB;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_OAK_FENCE;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_STICK;
	public static final DeferredItem<Item> PETRIFIED_ROTTEN_OAK_FENCE_GATE;
	public static final DeferredItem<Item> FOSSILIZED_SILT;
	public static final DeferredItem<Item> SEDGEBRUSH;
	public static final DeferredItem<Item> TALL_SEDGEBRUSH;
	public static final DeferredItem<Item> AMBER_GRIT;
	public static final DeferredItem<Item> COBBLED_AMBER_GRIT;
	public static final DeferredItem<Item> PLAQUE_HEART;
	public static final DeferredItem<Item> MEMORY_FRAGMENT;
	public static final DeferredItem<Item> DISTORTED_MEMORY_FRAGMENT;
	public static final DeferredItem<Item> RECOVERED_MEMORY_FRAGMENT;
	public static final DeferredItem<Item> STABILIZED_PALE_REMEDY;
	public static final DeferredItem<Item> RECOVERED_FADED_SWORD;
	public static final DeferredItem<Item> RECOVERED_FADED_AXE;
	public static final DeferredItem<Item> RECOVERED_FADED_PICKAXE;
	public static final DeferredItem<Item> RECOVERED_FADED_HOE;
	public static final DeferredItem<Item> RECOVERED_FADED_SHOVEL;
	public static final DeferredItem<Item> NULLSTONE;
	public static final DeferredItem<Item> PETRIFIED_RESIN;
	public static final DeferredItem<Item> COMPACT_PETRIFIED_RESIN;
	public static final DeferredItem<Item> FADED_DRIED_KELP;
	public static final DeferredItem<Item> FADED_BEETROOT;
	public static final DeferredItem<Item> FADED_ENCHANTED_GOLDEN_APPLE;
	public static final DeferredItem<Item> CRACKED_NULLSTONE;
	public static final DeferredItem<Item> MEMORY_QUARTZ;
	public static final DeferredItem<Item> SINKING_ASH;
	public static final DeferredItem<Item> MEMORY_SHARD;
	public static final DeferredItem<Item> RESONANT_ROT_EFFIGY;
	public static final DeferredItem<Item> COBBLED_NULLSTONE;
	public static final DeferredItem<Item> NULLSTONE_SLAB;
	public static final DeferredItem<Item> NULLSTONE_STAIR;
	public static final DeferredItem<Item> NULLSTONE_WALL;
	public static final DeferredItem<Item> COBBLED_NULLSTONE_SLAB;
	public static final DeferredItem<Item> COBBLED_NULLSTONE_STAIR;
	public static final DeferredItem<Item> COBBLED_NULLSTONE_WALL;
	public static final DeferredItem<Item> NULL_POINTERAXE;
	public static final DeferredItem<Item> STILT_WALKER_SPAWN_EGG;
	public static final DeferredItem<Item> SCANDERE_LIGNUM;
	public static final DeferredItem<Item> SCANDERE_LIGNUM_LOG;
	public static final DeferredItem<Item> LIGNUM_GIGAS_SPAWN_EGG;
	public static final DeferredItem<Item> FALSE_OAK_PLANKS;
	public static final DeferredItem<Item> LIGNUM_VERMIS_SPAWN_EGG;
	public static final DeferredItem<Item> FRACTUS_SPAWN_EGG;
	public static final DeferredItem<Item> FRACTUS_PRIME_SPAWN_EGG;
	public static final DeferredItem<Item> LIGNUM_PALUS_SPAWN_EGG;
	public static final DeferredItem<Item> FRACTUS_CORE;
	public static final DeferredItem<Item> FRACTUS_CORE_NUGGET;
	public static final DeferredItem<Item> FRACTUS_PRIME_CORE;
	public static final DeferredItem<Item> LIGNUM_CARO;
	static {
		BACKWOODS = REGISTRY.register("backwoods", BackwoodsItem::new);
		SPLINTER_SPAWN_EGG = REGISTRY.register("splinter_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.SPLINTER, -7643606, -3632054, new Item.Properties()));
		HOLLOW_SPAWN_EGG = REGISTRY.register("hollow_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.HOLLOW, -9943521, -10861791, new Item.Properties()));
		LOG_SPLINTER_SPAWN_EGG = REGISTRY.register("log_splinter_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.LOG_SPLINTER, -8826332, -6984137, new Item.Properties()));
		ASH_WEAVER_SPAWN_EGG = REGISTRY.register("ash_weaver_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.ASH_WEAVER, -10527652, -855310, new Item.Properties()));
		ASH_ROSE = block(TheBackwoodsModBlocks.ASH_ROSE, new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON));
		FADED_BLOCK = block(TheBackwoodsModBlocks.FADED_BLOCK);
		PLAQUE = block(TheBackwoodsModBlocks.PLAQUE);
		SEEP = REGISTRY.register("seep", SeepItem::new);
		PALE_REMEDY = REGISTRY.register("pale_remedy", PaleRemedyItem::new);
		ROT_SPAWN_EGG = REGISTRY.register("rot_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.ROT, -6914706, -10263709, new Item.Properties()));
		ROTTEN_OAK_PLANKS = block(TheBackwoodsModBlocks.ROTTEN_OAK_PLANKS);
		ROTTEN_OAK_WOOD = block(TheBackwoodsModBlocks.ROTTEN_OAK_WOOD);
		ROTTEN_OAK_LOG = block(TheBackwoodsModBlocks.ROTTEN_OAK_LOG);
		GEODE_TELEPORTER = block(TheBackwoodsModBlocks.GEODE_TELEPORTER, new Item.Properties().fireResistant());
		ROTTEN_OAK_STAIR = block(TheBackwoodsModBlocks.ROTTEN_OAK_STAIR);
		ROTTEN_OAK_SLAB = block(TheBackwoodsModBlocks.ROTTEN_OAK_SLAB);
		ROTTEN_OAK_FENCE = block(TheBackwoodsModBlocks.ROTTEN_OAK_FENCE);
		ROTTEN_OAK_TRAPDOOR = block(TheBackwoodsModBlocks.ROTTEN_OAK_TRAPDOOR);
		ROTTEN_STICK = REGISTRY.register("rotten_stick", RottenStickItem::new);
		SPLINTER_SHARD = REGISTRY.register("splinter_shard", SplinterShardItem::new);
		ROTTEN_SWORD = REGISTRY.register("rotten_sword", RottenSwordItem::new);
		HEARTWOOD_SHARD = REGISTRY.register("heartwood_shard", HeartwoodShardItem::new);
		HEARTWOOD_ROTTEN_SWORD = REGISTRY.register("heartwood_rotten_sword", HeartwoodRottenSwordItem::new);
		ROTTEN_AXE = REGISTRY.register("rotten_axe", RottenAxeItem::new);
		ROTTEN_PICKAXE = REGISTRY.register("rotten_pickaxe", RottenPickaxeItem::new);
		ROTTEN_SHOVEL = REGISTRY.register("rotten_shovel", RottenShovelItem::new);
		ROTTEN_HOE = REGISTRY.register("rotten_hoe", RottenHoeItem::new);
		ROT_EFFIGY = REGISTRY.register("rot_effigy", RotEffigyItem::new);
		ROTTEN_OAK_BUTTON = block(TheBackwoodsModBlocks.ROTTEN_OAK_BUTTON);
		ROTTEN_OAK_GATE = block(TheBackwoodsModBlocks.ROTTEN_OAK_GATE);
		ROTTEN_OAK_PRESSURE_PLATE = block(TheBackwoodsModBlocks.ROTTEN_OAK_PRESSURE_PLATE);
		PALE_DRAUGHT_BOTTLE = REGISTRY.register("pale_draught_bottle", PaleDraughtBottleItem::new);
		PETRIFIED_ROTTEN_OAK_WOOD = block(TheBackwoodsModBlocks.PETRIFIED_ROTTEN_OAK_WOOD);
		BLINDSPOT_SPLINTER_SPAWN_EGG = REGISTRY.register("blindspot_splinter_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.BLINDSPOT_SPLINTER, -7643606, -3632054, new Item.Properties()));
		BLINDSPOT_SPLINTER_SPAWNER = block(TheBackwoodsModBlocks.BLINDSPOT_SPLINTER_SPAWNER, new Item.Properties().fireResistant());
		FADED_SWORD = REGISTRY.register("faded_sword", FadedSwordItem::new);
		FADED_AXE = REGISTRY.register("faded_axe", FadedAxeItem::new);
		FADED_PICKAXE = REGISTRY.register("faded_pickaxe", FadedPickaxeItem::new);
		FADED_HOE = REGISTRY.register("faded_hoe", FadedHoeItem::new);
		FADED_SHOVEL = REGISTRY.register("faded_shovel", FadedShovelItem::new);
		FADED_BREAD = REGISTRY.register("faded_bread", FadedBreadItem::new);
		FADED_APPLE = REGISTRY.register("faded_apple", FadedAppleItem::new);
		FADED_GOLDEN_APPLE = REGISTRY.register("faded_golden_apple", FadedGoldenAppleItem::new);
		FADED_CARROT = REGISTRY.register("faded_carrot", FadedCarrotItem::new);
		FADED_GOLDEN_CARROT = REGISTRY.register("faded_golden_carrot", FadedGoldenCarrotItem::new);
		FADED_COOKED_BEEF = REGISTRY.register("faded_cooked_beef", FadedCookedBeefItem::new);
		FADED_WHEAT = REGISTRY.register("faded_wheat", FadedWheatItem::new);
		FADED_COOKED_CHICKEN = REGISTRY.register("faded_cooked_chicken", FadedCookedChickenItem::new);
		FADED_COOKIE = REGISTRY.register("faded_cookie", FadedCookieItem::new);
		FADED_POTATO = REGISTRY.register("faded_potato", FadedPotatoItem::new);
		FADED_BAKED_POTATO = REGISTRY.register("faded_baked_potato", FadedBakedPotatoItem::new);
		FADED_MELON_SLICE = REGISTRY.register("faded_melon_slice", FadedMelonSliceItem::new);
		FADED_PUMPKIN_PIE = REGISTRY.register("faded_pumpkin_pie", FadedPumpkinPieItem::new);
		FADED_IRON_INGOT = REGISTRY.register("faded_iron_ingot", FadedIronIngotItem::new);
		FADED_GOLD_INGOT = REGISTRY.register("faded_gold_ingot", FadedGoldIngotItem::new);
		FADED_COPPER_INGOT = REGISTRY.register("faded_copper_ingot", FadedCopperIngotItem::new);
		FADED_NETHERITE_INGOT = REGISTRY.register("faded_netherite_ingot", FadedNetheriteIngotItem::new);
		FADED_GOLD_NUGGET = REGISTRY.register("faded_gold_nugget", FadedGoldNuggetItem::new);
		FADED_MUTTON = REGISTRY.register("faded_mutton", FadedMuttonItem::new);
		FADED_COOKED_MUTTON = REGISTRY.register("faded_cooked_mutton", FadedCookedMuttonItem::new);
		FADED_COOKED_PORKCHOP = REGISTRY.register("faded_cooked_porkchop", FadedCookedPorkchopItem::new);
		FADED_PORKCHOP = REGISTRY.register("faded_porkchop", FadedPorkchopItem::new);
		FADED_RAW_BEEF = REGISTRY.register("faded_raw_beef", FadedRawBeefItem::new);
		FADED_RAW_CHICKEN = REGISTRY.register("faded_raw_chicken", FadedRawChickenItem::new);
		FADED_RABBIT = REGISTRY.register("faded_rabbit", FadedRawRabbitItem::new);
		FADED_COOKED_RABBIT = REGISTRY.register("faded_cooked_rabbit", FadedCookedRabbitItem::new);
		FADED_COD = REGISTRY.register("faded_cod", FadedCodItem::new);
		FADED_COOKED_COD = REGISTRY.register("faded_cooked_cod", FadedCookedCodItem::new);
		THE_PETRIFIED_WEALD = REGISTRY.register("the_petrified_weald", ThePetrifiedWealdItem::new);
		PETRIFIED_LOG_SPLINTER_SPAWN_EGG = REGISTRY.register("petrified_log_splinter_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.PETRIFIED_LOG_SPLINTER, -9411498, -6984137, new Item.Properties()));
		PETRIFIED_WEALD_FOLIAGE = block(TheBackwoodsModBlocks.PETRIFIED_WEALD_FOLIAGE, new Item.Properties().rarity(Rarity.UNCOMMON));
		PETRIFIED_ROTTEN_SWORD = REGISTRY.register("petrified_rotten_sword", PetrifiedRottenSwordItem::new);
		PETRIFIED_BARK = REGISTRY.register("petrified_bark", PetrifiedBarkItem::new);
		SHARPENED_SPLINTER_SHARD = REGISTRY.register("sharpened_splinter_shard", SharpenedSplinterShardItem::new);
		PETRIFIED_ROTTEN_OAK_LOG = block(TheBackwoodsModBlocks.PETRIFIED_ROTTEN_OAK_LOG);
		PETRIFIED_STRIPPED_ROTTEN_OAK_LOG = block(TheBackwoodsModBlocks.PETRIFIED_STRIPPED_ROTTEN_OAK_LOG);
		PETRIFIED_ROTTEN_AXE = REGISTRY.register("petrified_rotten_axe", PetrifiedRottenAxeItem::new);
		PETRIFIED_ROTTEN_OAK_PLANKS = block(TheBackwoodsModBlocks.PETRIFIED_ROTTEN_OAK_PLANKS);
		PETRIFIED_ROTTEN_OAK_STAIRS = block(TheBackwoodsModBlocks.PETRIFIED_ROTTEN_OAK_STAIRS);
		PETRIFIED_ROTTEN_OAK_SLAB = block(TheBackwoodsModBlocks.PETRIFIED_ROTTEN_OAK_SLAB);
		PETRIFIED_ROTTEN_OAK_FENCE = block(TheBackwoodsModBlocks.PETRIFIED_ROTTEN_OAK_FENCE);
		PETRIFIED_ROTTEN_STICK = REGISTRY.register("petrified_rotten_stick", PetrifiedRottenStickItem::new);
		PETRIFIED_ROTTEN_OAK_FENCE_GATE = block(TheBackwoodsModBlocks.PETRIFIED_ROTTEN_OAK_FENCE_GATE);
		FOSSILIZED_SILT = block(TheBackwoodsModBlocks.FOSSILIZED_SILT);
		SEDGEBRUSH = block(TheBackwoodsModBlocks.SEDGEBRUSH);
		TALL_SEDGEBRUSH = doubleBlock(TheBackwoodsModBlocks.TALL_SEDGEBRUSH);
		AMBER_GRIT = block(TheBackwoodsModBlocks.AMBER_GRIT);
		COBBLED_AMBER_GRIT = block(TheBackwoodsModBlocks.COBBLED_AMBER_GRIT);
		PLAQUE_HEART = block(TheBackwoodsModBlocks.PLAQUE_HEART);
		MEMORY_FRAGMENT = REGISTRY.register("memory_fragment", MemoryFragmentItem::new);
		DISTORTED_MEMORY_FRAGMENT = REGISTRY.register("distorted_memory_fragment", DistortedMemoryFragmentItem::new);
		RECOVERED_MEMORY_FRAGMENT = REGISTRY.register("recovered_memory_fragment", RecoveredMemoryFragmentItem::new);
		STABILIZED_PALE_REMEDY = REGISTRY.register("stabilized_pale_remedy", StabilizedPaleRemedyItem::new);
		RECOVERED_FADED_SWORD = REGISTRY.register("recovered_faded_sword", RecoveredFadedSwordItem::new);
		RECOVERED_FADED_AXE = REGISTRY.register("recovered_faded_axe", RecoveredFadedAxeItem::new);
		RECOVERED_FADED_PICKAXE = REGISTRY.register("recovered_faded_pickaxe", RecoveredFadedPickaxeItem::new);
		RECOVERED_FADED_HOE = REGISTRY.register("recovered_faded_hoe", RecoveredFadedHoeItem::new);
		RECOVERED_FADED_SHOVEL = REGISTRY.register("recovered_faded_shovel", RecoveredFadedShovelItem::new);
		NULLSTONE = block(TheBackwoodsModBlocks.NULLSTONE);
		PETRIFIED_RESIN = REGISTRY.register("petrified_resin", PetrifiedResinItem::new);
		COMPACT_PETRIFIED_RESIN = REGISTRY.register("compact_petrified_resin", CompactPetrifiedResinItem::new);
		FADED_DRIED_KELP = REGISTRY.register("faded_dried_kelp", FadedDriedKelpItem::new);
		FADED_BEETROOT = REGISTRY.register("faded_beetroot", FadedBeetrootItem::new);
		FADED_ENCHANTED_GOLDEN_APPLE = REGISTRY.register("faded_enchanted_golden_apple", FadedEnchantedGoldenAppleItem::new);
		CRACKED_NULLSTONE = block(TheBackwoodsModBlocks.CRACKED_NULLSTONE);
		MEMORY_QUARTZ = block(TheBackwoodsModBlocks.MEMORY_QUARTZ);
		SINKING_ASH = block(TheBackwoodsModBlocks.SINKING_ASH);
		MEMORY_SHARD = REGISTRY.register("memory_shard", MemoryShardItem::new);
		RESONANT_ROT_EFFIGY = REGISTRY.register("resonant_rot_effigy", ResonantRotEffigyItem::new);
		COBBLED_NULLSTONE = block(TheBackwoodsModBlocks.COBBLED_NULLSTONE);
		NULLSTONE_SLAB = block(TheBackwoodsModBlocks.NULLSTONE_SLAB);
		NULLSTONE_STAIR = block(TheBackwoodsModBlocks.NULLSTONE_STAIR);
		NULLSTONE_WALL = block(TheBackwoodsModBlocks.NULLSTONE_WALL);
		COBBLED_NULLSTONE_SLAB = block(TheBackwoodsModBlocks.COBBLED_NULLSTONE_SLAB);
		COBBLED_NULLSTONE_STAIR = block(TheBackwoodsModBlocks.COBBLED_NULLSTONE_STAIR);
		COBBLED_NULLSTONE_WALL = block(TheBackwoodsModBlocks.COBBLED_NULLSTONE_WALL);
		NULL_POINTERAXE = REGISTRY.register("null_pointeraxe", NullPointeraxeItem::new);
		STILT_WALKER_SPAWN_EGG = REGISTRY.register("stilt_walker_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.STILT_WALKER, -7643606, -13619152, new Item.Properties()));
		SCANDERE_LIGNUM = block(TheBackwoodsModBlocks.SCANDERE_LIGNUM);
		SCANDERE_LIGNUM_LOG = block(TheBackwoodsModBlocks.SCANDERE_LIGNUM_LOG);
		LIGNUM_GIGAS_SPAWN_EGG = REGISTRY.register("lignum_gigas_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.LIGNUM_GIGAS, -3632054, -7643606, new Item.Properties()));
		FALSE_OAK_PLANKS = block(TheBackwoodsModBlocks.FALSE_OAK_PLANKS);
		LIGNUM_VERMIS_SPAWN_EGG = REGISTRY.register("lignum_vermis_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.LIGNUM_VERMIS, -8366813, -10592674, new Item.Properties()));
		FRACTUS_SPAWN_EGG = REGISTRY.register("fractus_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.FRACTUS, -9021396, -8224126, new Item.Properties()));
		FRACTUS_PRIME_SPAWN_EGG = REGISTRY.register("fractus_prime_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.FRACTUS_PRIME, -9021396, -9568256, new Item.Properties()));
		LIGNUM_PALUS_SPAWN_EGG = REGISTRY.register("lignum_palus_spawn_egg", () -> new DeferredSpawnEggItem(TheBackwoodsModEntities.LIGNUM_PALUS, -9021396, -14211289, new Item.Properties()));
		FRACTUS_CORE = block(TheBackwoodsModBlocks.FRACTUS_CORE, new Item.Properties().stacksTo(1).rarity(Rarity.RARE));
		FRACTUS_CORE_NUGGET = REGISTRY.register("fractus_core_nugget", FractusCoreNuggetItem::new);
		FRACTUS_PRIME_CORE = block(TheBackwoodsModBlocks.FRACTUS_PRIME_CORE, new Item.Properties().stacksTo(1).rarity(Rarity.RARE));
		LIGNUM_CARO = block(TheBackwoodsModBlocks.LIGNUM_CARO);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), properties));
	}
}