modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="legendary_monsters"
version="1.21.1"
displayName="legendary_monsters"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.legendary_monsters]]
modId="neoforge"
type="required"
versionRange="1.20.1,1.21.1"
ordering="NONE"
side="BOTH"
[[mixins]]
config="legendary_monsters.mixins.json"
[[dependencies.legendary_monsters]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"