modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://discord.gg/nullnullnullnull"

[[mods]]
modId="thebrokenscript"
version="2.0.3"
displayName="The Broken Script"
updateJSONURL="https://api.modrinth.com/updates/the-broken-script/forge_updates.json?neoforge=only"
displayURL="https://modrinth.com/mod/the-broken-script"
logoFile= "logo.png"
credits=":wendigodrip:, for creating the original mod"
authors="Writers of the Script"
description='''Here I am.'''

[[mixins]]
config="thebrokenscript.mixins.json"

[[mixins]]
config="thebrokenscript-neoforge.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.thebrokenscript]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.227,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thebrokenscript]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thebrokenscript]]
    modId = "brokencore"
    type = "REQUIRED"
    versionRange = "[0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.thebrokenscript]]
    modId = "extensibleenums"
    type = "REQUIRED"
    versionRange = "[0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.thebrokenscript]]
    modId = "embeddium"
    type = "INCOMPATIBLE"
    reason = "use sodium instead"

[[dependencies.thebrokenscript]]
    modId = "oculus"
    type = "INCOMPATIBLE"
    reason = "use iris instead"

[[dependencies.thebrokenscript]]
    modId = "iris"
    type = "INCOMPATIBLE"
    reason = "We are aware Iris is incompatible right now. We are working on fixing it."
