modLoader = "javafml"
loaderVersion = "[1,)"
logoFile = "logo.png"
authors = "Serene Wave Studio | Timeless Squad"
license = "GPL3 / CC BY-NC-ND 4.0"

[[mods]]
modId = "tacz"
version = "1.1.8-hotfix-r6"
displayName = "Timeless & Classics Guns: Zero"
description = '''
'''

[[mixins]]
config = "tacz.mixins.json"

[[mixins]]
config = "tacz.compat.acceleratedrendering.mixins.json"

[[dependencies."{id}"]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."{id}"]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"